#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:26 PDT 2008
#
###################################################################################
fh=$1
totaltime=$2
starttime=$3
rtttouse="rtt_1"

for ports in `cat ports | awk '{ if (NR>1) print $1"#"$2 } '`
do
	(

	port=`echo $ports| sed 's/#.*//'`
	proto=`echo $ports|sed 's/.*#//'`
	cd $port
	app=${port}
	for params in `echo reqthink interRRE`
	do
		massage_reqthink param_${params}initial_${app}_${fh}ip ${rtttouse} ipmaps_${app}_numbers 2
		massage_reqthink param_${params}initial_${app}_${fh}0ip ${rtttouse} ipmaps_${app}_numbers 0 
		massage_reqthink param_${params}initial_${app}_${fh}1ip ${rtttouse} ipmaps_${app}_numbers 1 
	done
	preparespecs.all ${app} ${fh} ${totaltime} ${starttime}
	)
done
