#!/bin/bash -f
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:27 PDT 2008
#
###################################################################################
SWINGHOME=$1
TOPODIR=$2
export PERLLIB=/usr/lib/perl/5.8.0
export DEPLOYMENT_path=/home/`whoami`/bin/modelnet

hosts=${SWINGHOME}/hosts.xml

export LATESTTOPO=${SWINGHOME}/bin/latest
mkdir -p ${LATESTTOPO}
cd ${TOPODIR}

source ${TOPODIR}/this_cmd_line_allpairs

cp ${hosts} .

${SWINGHOME}/bin/kashi2inet -f ${TOPODIR}/specs_file > assigned_topo_with_clients_and_link_specs.graph
`echo ${allpairscmd}` > example.route
$DEPLOYMENT_path/mkmodel assigned_topo_with_clients_and_link_specs.graph hosts.xml > example.model
$DEPLOYMENT_path/genhosts example.model|sed 's/^vn/client/' > hosts
cp hosts.xml hosts example.model example.route ${LATESTTOPO}/
