#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:28 PDT 2008
#
###################################################################################

if [ "$#" -lt "2" ]
then
	echo "Usage $0 <ipmaps> <connfile>"
	exit
fi

# RAtio should be based on the percentage of request bytes going from side

ipmapfile=$1
connfile=$2
(
cat $ipmapfile | sed 's/^/ipmap /'
cat $connfile | grep -v '^#'
) | awk '{
	if($1=="ipmap") side[$2]=$3;
	else{
	#	print ; 
		src=$1;
		pairs=$8;
		req=0;
		rsp=0;
		for(i=9;i<=NF;i++)
		{
			if($i=="REQ") {
				req+=$(i+1);
	#			print " REQ " $i
			} else if($i=="RSP") {
				rsp+=$(i+1);
				
			}
			
		}
		if(side[src]=="0") {
			req0+=req;
			rsp1+=rsp;
			req0s+=pairs
		}
		else {req1+=req;
			rsp0+=rsp;
			req1s+=pairs
		}

		#print " side " side[src] " req0 " req0 " req1 " req1;
	}

} END { 
if(rsp1>0) printf "%d %d %.4f %.4f\n", rsp0, rsp1, rsp1/(rsp1+rsp0), rsp0/rsp1;
	  else printf "%d %d %.4f %.4f\n", rsp0, 1 , 0.01, 0.99;
}'
