#!/bin/bash 
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:29 PDT 2008
#
###################################################################################

if [ "$#" -lt "1" ]
then
	echo "Usage $0 <vnnum> <t_to_start> "
	exit
fi

function quitscript {
	echo "Error running generator_daemon " $vnnum " error $?  (`gettimeofday`)" >> ${common_file}
	exit -1
}

vnnum=$1
t_to_start=$2
source ./params.file
source ./paramsforscript
source ./psizeparam
source ./JOBVARIABLES
cd ${SWINGHOME}
mkdir -p ${tmpindifilesdir}
mkdir -p ${tmpoutputdir}
rm -rf ${tmpoutputdir}/$vnnum
touch ${tmpoutputdir}/$vnnum
cp ${indifilesdir}/indifile.vn$vnnum ${tmpindifilesdir}/indifiles.vn$vnnum
echo "Starting client vn $vnnum " > ${tmpoutputdir}/${vnnum}
PKTSIZE=`${SWINGHOME}/bin/gettopofield ${psizevalstrace} $vnnum 5`

if [ "$PKTSIZE" == "" ]
then
	PKTSIZE=1480
fi
if [ "$psize" == "max" ]
then
	PKTSIZE=1352
fi
if [ "$psize" == "min" ]
then
	PKTSIZE=300
fi
if [ "$PKTSIZE" -lt "100" ]
then
	PKTSIZE=100
fi
echo " pktsize $PKTSIZE $vnnum `/bin/hostname` gexec" >>pktsizeSwing
${generator_daemon} ${tmpindifilesdir}/indifiles.vn$vnnum ${t_to_start} ${PKTSIZE} ${REQTHINK} ${INTERCONN} ${INTERRRE} 2>> ${tmpoutputdir}/$vnnum >> ${tmpoutputdir}/$vnnum  || quitscript
ls ${common_file} >/dev/null
sleep 5
echo "Finished client vn $vnnum " > ${tmpoutputdir}/${vnnum}
echo $vnnum >> ${common_file}
ls ${common_file} >/dev/null
