#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:30 PDT 2008
#
###################################################################################
if [ "$1" == "" ]
then
	KILLTIME=999999
else
	KILLTIME=$1
fi
source ./params.file
source ./JOBVARIABLES
function quitscript {
	echo "Error in generator_daemon of some..."
	cat ${common_file} | grep -i error
	exit -1
}
cat </dev/null> ${common_file}
i=0;
t_to_start=`gettimeofday`
t_to_start=$((t_to_start+30))
s=0;
for file in `ls ${indifilesdir}/indifile*`
do
     vnnum=`echo $file|sed 's/.*\.vn//'`
	 vnrun -d $vnnum $modelfile -h $hostsfile ${gexec_script} $vnnum  ${t_to_start}|| quitscript
	 i=$((i+1))
	 s=$((s+1))
	 if [ "$s" == "150" ]
	 then
	   sleep 1
	   s=0;
 	 fi

done

numlines=0
SECONDS=0
SLEEPTIME=5
while [ "$numlines" -lt "$i" ]
do
	if [ "$KILLTIME" -lt "$SECONDS" ]
	then
		echo "TIMEOUT after $SECONDS secs"
		exit
	fi
	error=`grep -i error ${common_file}| grep -v "error 137"`
	if [ "$error" != "" ]
	then
	echo "exiting because of kickoffclients"
	echo $error
	cat ${common_file}
		quitscript
	fi
	echo -n total $i clients, $numlines over
	echo -n " "sleep $SLEEPTIME for clients to catchup time waiting is $SECONDS ""
	sleep $SLEEPTIME
	numlines=`cat ${common_file} | wc -l | awk '{ print $1 }'`
	echo -ne "\r"
done

echo total $i clients, $numlines over total time taken $SECONDS seconds "                                                                                  "

