#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:30 PDT 2008
#
###################################################################################
source ./params.file
un=`uname`
if [ "$un" != "FreeBSD" ]
then
	killall -9 generator_daemon || echo " no generator daemon"
	killall -9 listener || echo " no listener "
	killall -9 killsecs || echo " no killsecs "
	killall -9 sar
	killall -9 sadc
	killall -9 startsarfiles
	killall -9 hostgather_script || echo "no hostgather_script"
	for pss in `ps -awux | grep vmstat | awk '{ print $2}'` 
	do
	 kill -9 $pss
	done
	for pss in `ps -awux | grep getcpuusage | awk '{ print $2}'` 
	do
	 kill -9 $pss
	done
	sleep 5
	killall -9 sleep
	killall -9 vnrunhost || echo " no vnrunhost "
else
	echo " killing for core "	
	killall -9 killsecs || echo " no killsecs "
	echo "vmstat start"
	ps -auwx | grep vmstat
	echo "vmstat end"
	for pss in `ps -awux | grep vmstat | awk '{ print $2}'` 
	do
	echo " kill $pss " 
	 sudo kill -9 $pss
	done
	for pss in `ps -awux | grep getcpuusage | awk '{ print $2}'` 
	do
	 sudo kill -9 $pss
	done
	for pss in `ps -auwx | grep sar | awk '{ print $2}'`
	do
		sudo kill -9 $pss
	done
	for pss in `ps -auwx | grep startsarlogging | awk '{ print $2}'`
	do
		sudo kill -9 $pss
	done
	for pss in `ps -auwx | grep hostgather| awk '{ print $2}'`
	do
		sudo kill -9 $pss
	done
	sleep 5
	killall -9 sleep
	killall -9 vnrunhost || echo " no vnrunhost "
fi
