#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:31 PDT 2008
#
###################################################################################
source params.file
source paramsforscript

export maxmem=${maxmem}
# below if try7
# below just to vary middle
if [ "${variablemax}" == "1" ]
then
	latestvals=1
fi
if [ "${latestvals}" == "1" ]
then
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.ipv4.tcp_rmem="4096 ${maxmem} 174760"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.ipv4.tcp_wmem="4096 ${maxmem} 131072"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.ipv4.tcp_mem="196608 262144 393126"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.core.rmem_max="${maxmem}"' 
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.core.wmem_max="${maxmem}"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.core.rmem_default="80000"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.core.wmem_default="80000"'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.ipv4.tcp_bic=1'
hostrun ${modelfile} 'sudo /sbin/sysctl -w net.ipv4.tcp_vegas_cong_avoid=0'
fi

