#!/bin/bash
###################################################################################
# 
#  Copyright (C) 2008 Kashi Venkatesh Vishwanath <swingxficgenerator@gmail.com>
# 
#  Permission is hereby granted, free of charge, to any person obtaining a copy of
#  this software and associated documentation files (the "Software"), to  deal  in
#  the Software without restriction, including without limitation  the  rights  to
#  use, copy, modify, merge, publish, distribute, sublicense, and/or  sell  copies
#  of the Software, and to permit persons to whom the Software is furnished to  do
#  so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in  all
#  copies of the Software and its documentation and acknowledgment shall be  given
#  in the documentation  and  software  packages  that  this  Software  was  used.
#  
#  You should have received a copy of the GNU Library General Public License along
#  with this library; if not, write to the  Free  Software  Foundation,  Inc.,  59
#  Temple Place, Suite 330, Boston, MA 02111-1307, USA.
# 
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY  OF  ANY  KIND,  EXPRESS  OR
#  IMPLIED, INCLUDING BUT  NOT  LIMITED  TO  THE  WARRANTIES  OF  MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO  EVENT  SHALL  THE
#  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR  OTHER  LIABILITY,  WHETHER  IN  AN
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF  OR  IN  CONNECTION
#  WITH  THE  SOFTWARE  OR  THE  USE  OR   OTHER   DEALINGS  IN   THE   SOFTWARE.
#
#
#
#  Last Modified : Thu Sep 18 22:48:34 PDT 2008
#
###################################################################################
if [ "$#" -lt "1" ]
then
	echo "Usage: $0 <time> <startime> <nettracedir>"
	exit
fi


gotothisdir=`pwd`
source JOBVARIABLES
cd ${gotothisdir}

SWINGHOME=$3


totaltime=$1
echo "state=doinganalysis" >> STATE
rm -f tlatest
rm -f tlatest.*
sleep 5

corename=`cat ${SWINGHOME}/bin/latest/hosts.xml | grep "<emul" | head -n 1 |sed 's/.*\"\(.*\)\".*/\1/'`


tcpdump -nn -r ${SWINGHOME}/latest-trace/tlatest.raw.${corename} dst net 10.0.0.0/16 | IP_10_128 | convert_date_precision | getduration - $1 $2  >> tlatest

for fnames in `echo tlatest `
do
	echo "$fnames"
	separateline="0_1_separate ${fnames} ${SWINGHOME}/bin/latest/hosts `pwd`/cdfdir/inputforgeneric_UDP"
	for i in `cat ports | awk '{ if(NR>1) print $3 }'`
	do
		separateline=${separateline}" `pwd`/cdfdir/inputforgeneric_$i"
	done
	`echo $separateline`
done

starttime=`head -n 1 tlatest|awk '{ printf "%.4f",$1}'`
wait
